### ISSUE TITLE
request: custom startup logo

### ISSUE THREAD

**Issue by ideasman69** [superdavex/Sony-XAV-AX100#3]
Hi superdave,

Firstly - love your work! The warning screen is one of those things you don't look for when deciding on a headunit but ended up driving me nuts. Having the option to remove it has made my day! So thanks again.

This isn't an issue, but more of a request / question. Is it possible to replace the stock SONY screen at startup with a custom image?

Cheers!

**Comment by superdavex** [comment]
Posting this response here as well for visibility.

> It's doable. The logo is in a partition called "logo". The image is a raw 800x480 RGB32 pixel definition. This is set before you get serial access in uboot so it could be risky if something went wrong. There are checks for the partition magic and it doesn't seem like there would be any issues if it was bad. I may try it on my test unit when I get a chance. If my firmware is flashed it would be simple to write a script to update it from usb

**Comment by baggar11** [comment]
+1 for this too. Would be a really nice touch.

**Comment by aldovia** [comment]
Hi superdavex, your work here looks terrific. I just installed the new XAV-AX200, and didn’t realise that annoying warning screen would be there. It’s a massive pain and Sony won’t address the issue. Isn’t it enough to acknowledge it once?

Anyway I assume I can’t use your AX100 firmware for my AX200, would you consider adding support for this one issue? Seems to bother a lot of users (based on comments on Sony’s website from users). Regards, Dan.

**Comment by superdavex** [comment]
Hey Dan, I would be glad to add it for the AX200, but, we either need to get a MCU update for it or find a way to get into setup without it.  The mcu bin for the AX100 is a different version.

**Comment by aldovia** [comment]
Ok, thanks for for the reply. Is there anything I can do with my device to get that, or is it a matter of waiting until Sony publish a firmware update for it? The start up time is disappointingly long too, but I think the AX100 has the same problem. Cheers mate.

**Comment by colross** [comment]
Cheers m8 - this is fantastic.
Just to pull this thread back to its origin, changing the splash screen would be mighty fine!
Thank you for your work - just awesome!

**Comment by superdavex** [comment]
Added new util to change startup logo
https://github.com/superdavex/Sony-XAV-AX100/tree/master/ChangeLogo

**Comment by baggar11** [comment]
Awesome man! Just tried it out, worked great. Thanks!

![img_20180111_163841](https://user-images.githubusercontent.com/4692679/34855595-76d843ec-f6f5-11e7-9005-43e96f6e87cf.jpg)

**Comment by ideasman69** [comment]
@superdavex is a boss! thanks heaps man. this headunit just keeps getting better and better.

**Comment by colross** [comment]
Thats awesome... I am going to do this as soon as I get a design! Thanks @superdavex !!!

**Comment by superdavex** [comment]
Looks good @baggar11 !
@colross feel free to use the Smart Car logo ;)

**Comment by ghost** [comment]
OMG - this is awesome - thanks again @superdavex !!!
Its not quite a Smart Car logo - its a couple of designs that I found online, munged together and prettied up.
Photo of radio is a little washed out, but I have attached the original image in its full glory. It looks great when starting up!

![img_4843](https://user-images.githubusercontent.com/210859/34875493-11d4ed92-f763-11e7-9cd3-ab0da4aa0fb5.JPG)
![my_new_logo](https://user-images.githubusercontent.com/210859/34875501-16cfc862-f763-11e7-8a72-45fe1b1b6ec6.jpg)

**Comment by superdavex** [comment]
Ha, yeah not quite.  Looks great!

**Comment by ideasman69** [comment]
Thanks again @superdavex, feels like a stock HU now :)

![img_1317](https://user-images.githubusercontent.com/19260137/35310706-cd040768-0106-11e8-9bb3-54bf6c2e542b.jpg)

**Comment by b-ongo** [comment]
Is there a way to do this manually on a Mac rather than using the .bat prompts?

**Comment by butchm100** [comment]
Superdavex, first of all I am so glad I ran across your thread. My name is William Mann I just purchased a Sony XAV AX100 for my Chevy truck it has the latest version update it is 1.02.09. I would be thrilled if the start up page had a Chevrolet logo in place of the Sony logo but I am 74 years old & pretty much Tech illiterate. Would it be possible for you to sell me a USB drive with the firmware I need loaded that I can plug it in & download  to my head unit? I don't care if it just says "Chevrolet" or is a picture of a Chevy "Bowtie" or both. I would be eternally grateful. Thanks butchm100. My email is  mann945@bellsouth.net.

**Comment by MrMaps79** [comment]
Thanks to the brains behind this! Loving the "factory" feel I get when starting up the LC100. Took some time, but I managed to find the right font LandCruiser name logo to suit the 100 series, then put it together with a crisp Toyota elipse logo to make the final product for the new startup screen.
![20201115_114206](https://user-images.githubusercontent.com/52368613/101481186-de316480-39a8-11eb-83b8-ec6e2086dd99.jpg)

**Comment by MrMaps79** [comment]
For anyone else with a 100 series, or possibly even an 80 series, here is the image I put together for the startup screen in mine. Feel free to use!!
![20201114_170034](https://user-images.githubusercontent.com/52368613/101482980-9f50de00-39ab-11eb-85c6-de12b0562f46.png)

**Comment by MrMaps79** [comment]
And here's another I made up, which is better suited to 75 Series and the rest that use the same font. Once again, feel free to use!
![20201113_194753](https://user-images.githubusercontent.com/52368613/101483163-e0e18900-39ab-11eb-88e6-ebf886dc6dc2.png)

**Comment by fenicexy** [comment]
Good mornig is possible to make te same step for sony XAV-1005DB?
