### ISSUE TITLE
Read Error: Please use other USB devices and Reset press button

### ISSUE THREAD

**Issue by jckmlvny** [superdavex/Sony-XAV-AX100#6]
It started to update, then got an image of how to press reset button and "installing" in a loop, then,

"Read Error: Please use other USB devices and press Reset button"

Please advise

**Comment by superdavex** [comment]
That generally means it doesn't like the USB stick.  Try another stick.  The smaller the better, USB2 preferably.

**Comment by jckmlvny** [comment]
I just got it to work with a different USB stick, a SansDisk. It was actually 16GB. The stick that got me into trouble was a 2GB tradeshow unbranded POS. So try something different is the lesson I guess. 

 Thanks for the speedy response.
