### ISSUE TITLE
need help with bad firmware flash

### ISSUE THREAD

**Issue by batmite** [superdavex/Sony-XAV-AX100#8]
hi superdavex! i kinda need help with the modded firmware, long story short after 50% first reboot, my headunit got stock on the sony logo and it just keeps rebooting to the logo, is there any chance of recovering the unit with the official firmware?

**Comment by superdavex** [comment]
Hey, sorry to hear that. Can you give more details how you got to these. You were loading my modded firmware? It started In the mcu flash, then rebooted to the updater and started flashing there? How far did it get, was there any error message. Is the USB drive in while your rebooting?

**Comment by batmite** [comment]
hi superdave, i downloaded the update.zip file from from your repo, extracted it to the same usb key i used to update the headunit, the usb key had the official firmware in the update folder, so i just overwritten the files from your modded update.zip to the update folder, then inserted it to the usb port and went to settings click on firmware which displayed 1.02.06, then clicked on update which showed 1.02.07 then proceeded with the update, progress bar got to 50% rebooted to sony logo, and it goes back to the sony logo every 10 secs. i didnt notice any error message while updating just showed  50% then rebooted and that was it. yeah i didnt remove the usb flash until the 4th reboot to the sony logo. it should have continued at 51% after the reboot but it didnt

**Comment by superdavex** [comment]
That's odd. So it installed the Mcu update and rebooted right to the Sony logo?  It didn't go into the update utility at all? When the mcu update starts a flag is set that forces the radio to go into isp update mode. It cant come out of that unless an update is processed and it sets that flag. You would see that though, my update doesn't change that until it gets to the end and it is successful. It's a fail safe in case something goes wrong. If it never went into update mode nothing was changed except the mcu. I didn't make any changes to that.

**Comment by batmite** [comment]
but is it still possible to revert back to official firmware?

**Comment by superdavex** [comment]
It doeskin seem like it ever flashed the modded firmware.  The first flash before the reboot is the mcu, that's stock.  You can try  extracting the usbexecute attched to a usb stick and inserting it on boot.
[usbexecute.zip](https://github.com/superdavex/Sony-XAV-AX100/files/1637557/usbexecute.zip)

If it flashed the modded firmware it would write a file called testing.txt to the stick.

At this point we dont have a way to get into the isp update mode without coming from the settings menu.  If the update installed at all, the first thing is does is enable the UART port.  You would have to solder a connector on for that though.

**Comment by batmite** [comment]
ok i'll give it a go, do i put the file inside the update folder too?  if it didn't create the file? what would that mean?

**Comment by batmite** [comment]
anyway i tried putting the file the root directory, and inside the update folder with no other files, inserted it in the usb port then switched on the head unit waited for 3 reboots then removed the usb, but there wasnt any files added to the stick

**Comment by superdavex** [comment]
That means either the firmware didn't flash or it doesn't get far enough for the USB to be detected and the script execute.  The only other hope would be if the UART was enabled or we find a way to enter setup from boot.  I haven't been able to find any way to do that so far.

**Comment by batmite** [comment]
if i can get a usb to uart programmer can i recover the official firmware with it?

**Comment by batmite** [comment]
Hi superdave! i finally was able to fix the headunit! I just removed the usb extender cable then plugged the usb key directly to the usb port of the xav ax100 then the updater continued installing. it was probably a loose connection. thanks again!

**Comment by superdavex** [comment]
Glad you got it going. That's interesting that the extender wouldn't let it go into setup. Good to know.  I'll look at the UART output later and see what's it's doing.

**Comment by st-ivan** [comment]
https://github.com/superdavex/Sony-XAV-AX100/issues/8#issuecomment-358197749

glad you got ot working. im stuck at 50% update boot loop.. tried dozens of usb none of them worked. i think i havent tried removing the usb extender. can you even remove the usb cable and connect direclty to the usb port? im pretty sure my cable is directely conected to the motherboard (cant be removed)
